<?php


class OmStationenTexter
{

    var $texts;

    public function __construct($language)
    {
        if ($language == 'sv'){
            $this->texts = $this->getTextsSv();
        }

        if ($language == 'en'){
            $this->texts = $this->getTextsEn();
        }

    }

    function getTextsSv(){

        $texts = array(
            'page-title' => 'Om stationen',
            'header' => 'Om stationen',
            'header-text' => 'Fagelstationen grundades 19XX. En stationsbyggnad byggdes mellan Falsterbo kyrka och Falsterbo museum. Stationen drivs av Skånes ornitologiska förening. ',
            'lokal' => '-------------------------------------',
            'VERKSAMHET' => '',
            'verksamhet-header' => 'Verksamhet',
            'verksamhet-forskning' => 'Forskning',
            'verksamhet-intro' => 'All verksamhet som fågelstationen bedriver har sitt ursprung i forskning. Ända sedan starten har stationen varit knuten till Lunds Universitet och genom åren har många doktorander gjort hela eller delar av sitt fältarbete på Falsterbo fågelstation. En del av denna ekologiska grundforskning kan kanske te sig abstrakt för gemene man, men rönen vidgar vår förståelse om världen och fåglarna. Inom ramen för denna ständigt pågående grundforskning finns det flera mer handfasta tillämpningar enligt nedan.',
            'verksamhet-sub-header-mon' => 'Storskalig miljöövervakning',
            'verksamhet-mon-content-1' => 'Flyttande fåglar rör sig över oerhört stora områden. Fåglar som passerar Falsterbo på hösten kommer från sina häckningsplatser i norra Europa. En del av dem har en lång resa kvar till sina vinterkvarter i Afrika. Genom att systematiskt följa fågelflyttningen förbi Falsterbo får vi därmed indikationer om förändringar i naturen, från Norra Europa till Afrika. Dessa förändringar pågår ständigt och berör allt liv på jorden. Klimat- och miljöfrågor står i världspolitikens fokus. Att följa miljöförändringar under lång tid är därför nödvändigt och fåglar är utmärkta indikatorer för detta!',
            'verksamhet-mon-content-2' => 'Falsterbo Fågelstation har många decenniers erfarenhet av sådan grundforskning. Vi har totalt fyra sammanhängande serier av systematiska och jämförbara data. Sträckräkningsdata sedan 1973 och ringmärkningsdata fyren vår och höst samt Flommen (höst) sedan 1980. Dessa serier blir allt värdefullare för varje år som läggs till. För att kunna garantera detta är fågelstationen beroende av Ditt stöd.',
            'verksamhet-sub-header-mon-loc' => 'Lokal miljöövervakning',
            'verksamhet-mon-loc-content' => 'Våra inventeringar av häckande och rastande fåglar har också pågått i flera decennier. Resultaten medför bl.a. att vi kan argumentera och agera i diverse exploateringsärenden i en alltmer tätbefolkad region. Trycket på naturen ökar för varje dag och för att beskriva fåglarnas behov och roll i ekosystemet behöver fågelstationen Ditt stöd.',
            'verksamhet-sub-header-edu' => 'Folkbildning',
            'verksamhet-edu-content' => 'En annan mycket viktig form av fågel- och naturskydd är att sprida kunskap och väcka intresse hos allmänheten, inte minst hos barn och ungdomar. Vi arbetar ständigt med detta genom guidningar, exkursioner, utställningar, hemsida m.m. Vi har bra material, duktiga guider och avser att fortsätta och ytterligare utveckla denna verksamhet. Till detta behöver fågelstationen Ditt stöd.',
            'verksamhet-stod-oss' => 'Vi behöver ditt stöd!',
            'verksamhet-stod-alla-bidrag' => 'Alla bidrag, stora som små, tas tacksamt emot.',
            'verksamhet-stod-las-mer' => 'Läs mer här!',
            'KONTAKT' => '',
            'kontakt-header' => 'Kontakt',
            'kontakt-finstilt' => 'Samt andra uppgifter',
            'STÖD' => '',
            'stod-header' => 'Stöd stationen',
            'stod-header-text' => 'Falsterbo Fågelstation är en ideell icke vinstdrivande verksamhet. Drivet kommer istället av att förstå mer om naturen i allmänhet, och om fåglar i synnerhet. Verksamheten bedrivs med mycket knappa ekonomiska resurser. Beslut om nedskärningar i anslag till natur- och miljövård riskerar att ytterligare försvåra arbetet. Vi behöver Ditt stöd.',
            'stod-typer' => 'Olika typer av stöd',
            'stod-li-1' => 'Du tycket det vi gör är vettigt och intressant',
            'stod-li-1-linktext' => 'ge ett rakt bidrag',
            'stod-li-2' => 'Någon som har "allt" fyller år ',
            'stod-li-2-linktext' => 'ge en hyllningsgåva',
            'stod-li-3' => 'Någon vän går bort',
            'stod-li-3-linktext' => 'ge en minnesgåva',
            'stod-li-4' => 'Det lackar mot jul',
            'stod-li-4-linktext' => 'ge en julklapp',
            'stod-li-5' => 'Du har inga direkta arvingar',
            'stod-li-5-linktext' => 'testamentera tillgångar till oss',
            'stod-90-1' => 'För att långsiktigt stärka verksamheten, och ytterligare öka trovärdigheten för, och transparensen i, stationens verksamhet, så har vi nu ett 90 konto.',
            'stod-90-2' => 'Det innebär garanti för att pengarna går till det ändamål som avses, eftersom insamlingen övervakas av Svensk Insamlingskontroll. ',
            'stod-90-3' => 'De skriver på sin hemsida: "Föreningen [Skånes Ornitologiska Förening] har erhållit 90-konto för en del av sitt ändamål; fågelforskning, fågelskydd samt undervisning om fåglar och fågelflyttning allt i regi av Falsterbo Fågelstation." Inkomna bidrag måste alltså användas till verksamheten vid Falsterbo Fågelstation, vilket också årligen i detalj skall redovisas till Svensk Insamlingskontroll.',
            'stod-90-nummer' => 'Pg 900301-3, Bg 900-3013, SKÅNES ORNITOLOGISKA FÖRENING',
            'stod-reach' => 'Stödet når fåglarna',
            'stod-90-huvudman' => 'Skånes Ornitologiska Förening (SkOF) är huvudman för Falsterbo Fågelstation. Vänligen ange därför vid inbetalning via 90-konton mottagaren Skånes Ornitologiska Förening.',
            'BIDRAG' => '',
            'bidrag-header' => 'Ett enkelt bidrag',
            'bidrag-intro-1' => 'Detta är det lättaste sättet att bidra till fågelstationens verksamhet och att också samtidigt bli en Falsterbo Fågelvän.',
            'bidrag-intro-2' => 'Du sätter in valfritt belopp på bg 900-3013 eller pg 900301-3, betalningsmottagare Skånes Ornitologiska Förening.',
            'bidrag-intro-3' => 'Ange "Gåva" samt namn, telefonnummer och e-postadress vid inbetalning.',
            'bidrag-intro-4' => 'Din gåva medför att Du blir en Falsterbo Fågelvän (om Du inte redan är det) och Du kommer att få fågelstationens nyhetsbrev (utkommer 2-3 ggr/år) och andra utskick.',
            'bidrag-intro-5' => 'Är Du intresserad av detta fyller Du i formuläret och godkänner samtidigt att vi sparar Dina kontaktuppgifter.',
            'bidrag-fv-1' => 'Falsterbo Fågelvän - vad är det?',
            'bidrag-fv-2' => 'Vad är syftet med Falsterbo Fågelvän?',
            'bidrag-fv-3' => 'Syftet är att förstärka Falsterbo Fågelstation ekonomiskt genom stöd från allmänheten i intervall som varje givare själv bestämmer. Då blir man fågelstationens långsiktiga supporter och bidrar till att vi kan fortsätta att föra fåglarnas talan.',
            'bidrag-fv-4' => 'Vem är Falsterbo Fågelvän?',
            'bidrag-fv-5' => 'Alla som på något sätt väljer att bidra ekonomiskt till vår verksamhet blir en Falsterbo Fågelvän! Detta blir man automatiskt.',
            'bidrag-fv-6' => 'Är du redan givare och finns i vårt register blir du också automatiskt Falsterbo Fågelvän.',
            'bidrag-fv-7' => 'Hur håller vi koll på våra Falsterbo Fågelvänner?',
            'bidrag-fv-8' => 'Vi för ett register över vilka som bidragit ekonomiskt till vår verksamhet. De data vi samlar in för varje bidragsgivare är: förnamn, efternamn, telefonnummer, e-postadress och datum för senaste bidrag.',
            'bidrag-fv-9' => 'Hur kommunicerar vi med våra Falsterbo Fågelvänner?',
            'bidrag-fv-10' => 'Som Falsterbo Fågelvän får man automatiskt löpande information från oss:',
            'bidrag-fv-l-1' => 'Nyhetsbrev från Falsterbo Fågelstation (minst 3 gånger per år)',
            'bidrag-fv-l-2' => 'Fågelstationens årsrapporter bl.a. från sträckräkning och ringmärkning',
            'bidrag-fv-l-3' => 'Annan intressant information om fågelstationens verksamhet (oregelbundet)',
            'bidrag-fv-l-4' => 'Alla utskick görs digitalt, dvs. vi skickar inget via vanlig post.',
            'bidrag-fv-11' => 'Hur länge är man en Falsterbo Fågelvän?',
            'bidrag-fv-2-1' => 'Vi gör löpande kontroller av vårt register och har man inte skänkt något ekonomiskt bidrag de senaste tre åren informeras man om detta och får en ny chans att skänka ett bidrag. Annars plockas man bort som Falsterbo Fågelvän.',
            'bidrag-fv-2-2' => 'Man kan aktivt höra av sig till oss (via mail eller telefon) och säga att man vill bli bortplockad ur vårt register.',
            'bidrag-fv-12' => 'Har Du frågor?',
            'bidrag-fv-13' => 'Kontakta Björn Malmhagen 0703-339499 eller Karin Persson 040-473703.',
            'bidrag-swish-1' => 'Du kan även Swisha pengar till oss via nummer 123 196 2455.',
            'bidrag-swish-2' => 'Om du använder Swish skulle vi vara tacksamma för ett kort email där du berättar vem du är. Skicka detta till <a href="mailto:falsterbo@skof.se">falsterbo@skof.se</a>. ',
            'MINNESGÅVA' => '',
            'minnesgava-header' => 'Minnesgåva',
            'minnesgava-intro' => 'Minnesgåva',
            'HYLLNINGSGÅVA' => '',
            'hyllningsgava-header' => 'Hyllningsgåva',
            'hyllningsgava-para-1' => 'Att ge en hyllningsgåva till välgörande ändamål är en uppskattad handling. Du kan skänka en sådan gåva till Falsterbo Fågelstation, genom att sätta in valfritt belopp på vårt 90-konto (bg 900-3013, pg 900301-3, Skånes Ornitologiska Förening). Välj sedan ett färdigt hyllningsbrev eller skriv en egen hälsning.',
            'hyllningsgava-para-2' => 'Så snart Ditt bidrag registrerats av vår bank skickar vi det önskade hyllningsbrevet till den adress Du angivit.',
            'hyllningsgava-para-3' => 'I särskilt brådskande fall ber vi Dig ta telefonkontakt (0736-254 256), så att vi säkert hinner fixa allt i tid.',
            'hyllningsgava-motiv' => 'Motiv',
            'hyllningsgava-mottagare' => 'Mottagare (jubilar)',
            'hyllningsgava-mottagare-' => 'Mottagare',
            'hyllningsgava-givare' => 'Givare',
            'hyllningsgava-hyllning' => 'Hjärtliga gratulationer på ... ',
            'hyllningsgava-inbetalare' => 'Inbetalare',
            'ARVSGÅVA' => '',
            'arvsgava-header' => 'Arvsgåva',
            'arvsgava-para-1' => 'Ett testamente är Din sista vilja och får stor betydelse efter Din bortgång. Du kan testamentera Dina tillgångar, helt eller delvis, till Falsterbo Fågelstation. Väljer Du att göra detta bidrar Du bland annat till att väcka naturintresse hos kommande generationer och därigenom också skapa en bättre framtid för fåglarna.',
            'arvsgava-para-2' => 'Att upprätta ett testamente behöver i regel inte vara svårare än att med egna ord skriva att "så här vill jag att min kvarlåtenskap ska fördelas när jag själv är borta..."',
            'arvsgava-para-3' => 'Det finns dock vissa formella krav och vi rekommenderar därför att Du kontaktar Din bank eller en jurist.',
            'arvsgava-data' => 'De uppgifter Du behöver från oss är',
            'arvsgava-gåvomottagare' => 'Gåvomottagare',
            'arvsgava-organisationsnummer' => 'Organisationsnummer',
            'arvsgava-bankgiro' => 'Bankgiro',
            'arvsgava-betalningsmottagare' => 'Betalningsmottagare',
            'arvsgava-contact' => 'Kontaktpersoner',
            'JUL' => '',
            'julgava-header' => 'Julgåva',
            'INTER' => '',
            'inter-header' => 'Internationellt samarbete',
            'inter-text-1' => 'Falsterbo fågelstation har ett formellt vänskapsavtal (Friendship Agreement) mellan oss, <a href="https://njaudubon.org/centers/cape-may-bird-observatory/">New Jersey Audubon\'s Cape May Bird Observatory</a> (USA), <a href="https://www.birdscanada.org/longpoint/">Long Point Bird Observatory</a> (Kanada) och <a href="https://www.spurnbirdobservatory.co.uk/">Spurn Bird Observatory</a> (UK). Genom detta avtal avser vi att arbeta med att främja internationella relationer för att stimulera till ökad miljömedvetenhet.',
            'inter-text-2' => 'Våra respektive medarbetare eller medlemmar kommer att gynnas av samarbetet genom särskilda rabatter för att främja besök på respektive fågelstation i syfte att sprida kunskap kring fågelflyttning på en internationell nivå. Nedan finns det avtal som kommer att vara vägledande framöver. Gemensamt kommer vi att ge uttryck för vad vårt arbete på fågelstationerna innebär för att utveckla nya sätt att svara på angelägna frågor om fåglar, deras livsmiljö, och ytterst, deras bevarande för framtida generationer.',
            'inter-perspektiv' => 'Perspektiv på vänskapsavtalet',
            'lokal' => '-------------------------------------'

        );

        return $texts;
    }

    function getTextsEn(){

        $texts = array(
            'page-title' => 'About us',
            'header' => 'About us',
            'header-text' => '',
            'lokal' => '',
            'VERKSAMHET' => '',
            'verksamhet-header' => 'What we do',
            'verksamhet-forskning' => 'Research',
            'verksamhet-intro' => 'Everything we do is tightly linked to research and science. There have been close collaboration between University of Lund and Falsterbo bird observatory ever since its foundation. Throughout the years many Ph.D students have done most, or parts of, their fieldwork with us. Some of the results from this ecological base research may, for a layman, sound very abstract, but the knowledge generated increase our understanding of the world at large, and of course our understanding of birds. Within this research framework we run a several more tangible and applied projects as seen below.',
            'verksamhet-sub-header-mon' => 'Global environmental monitoring',
            'verksamhet-mon-content-1' => 'Migrating birds cover vast distances. Birds passing by Falsterbo in the autumn have been breeding in Northern Europe. Some of them have still very far to go, when passing Falsterbo, before they reach their winter quarters in tropical Africa. Through systematic studies of the bird migration in Falsterbo we get indications of environment changes (in a wide sense) from the high Arctic to Africa. These changes, human induced or natural, never stop and affect all living organisms including humans. Over the last decades climate and environment has grabbed the attention of all and is now often at the centre of World politics. When climate change really started getting the attention, we had 20 years of data already. All this illustrates the need of long-term environmental monitoring. Birds are excellent indicators for this.',
            'verksamhet-mon-content-2' => 'Falsterbo bird observatory has vast experience of this type of research. We have four long-term series with systematically obtained and, thus comparable, data. We have visible migration data from 1973 and ringing data from the light house garden (autumn and spring) and Flommen reed beds since 1980. These series are becoming increasingly valuable by each year being added. To guarantee this, the Bird Observatory needs you support!',
            'verksamhet-sub-header-mon-loc' => 'Local environmental monitoring',
            'verksamhet-mon-loc-content' => 'Our work with repeated assessments of breeding and staging birds has also been ongoing for a long time. Also here, changes are detected. The data can be used to showcase the importance of the peninsula as a refuge for bird in an increasingly densely populated and built-up area. The pressure on nature is increasing week by week. To be able to voice the importance of birds and their role in the ecosystem, the bird observatory needs you support.',
            'verksamhet-sub-header-edu' => 'Awareness building',
            'verksamhet-edu-content' => 'A very important aspect of bird and nature protection is awareness raising among the general public. Children of all ages are here especially important, them being the future custodians of the environment. We constantly work with this through different means such as guiding of various groups, excursions, exhibitions, and of course our web site and also through various social media. We have good material, inspiring guides and intend to further strengthen this area of work. For this we need you support.',
            'verksamhet-stod-oss' => 'We need your support!',
            'verksamhet-stod-alla-bidrag' => 'All contributions regardless of size are much welcome.',
            'verksamhet-stod-las-mer' => 'Read more here',
            'STÖD' => '',
            'stod-header' => 'Support the bird observatory',
            'stod-header-text' => 'Falsterbo bird observatory is a non-profit entity. The driving force is instead a curiosity to understand more about nature in general and of course more about birds in particular. Our economy is very tight. High level decision on cuts ar changed focus in terms of governmental nature conservation priorities may have a huge impact on our possibilities continuing our work. We need you support.',
            'stod-typer' => 'Different types of support',
            'stod-li-1' => 'You simply believe what we do is sane and interesting',
            'stod-li-1-linktext' => 'chip in directly',
            'stod-li-2' => 'Someone who has "everything" has a birthday',
            'stod-li-2-linktext' => 'give a gift donation',
            'stod-li-3' => 'A dear friend pass away',
            'stod-li-3-linktext' => 'give a remembrance gift',
            'stod-li-4' => 'Christmas is coming up',
            'stod-li-4-linktext' => 'give someone a Christmas present',
            'stod-li-5' => 'You do not have any immediate heritors',
            'stod-li-5-linktext' => 'leave assets by a will to us',
            'stod-90-1' => 'In order to further support the work of the bird observatory over the long-term, we now have a "90 account".',
            'stod-90-2' => 'A "90 account" is subject to certification via "The Swedish Fundraising Control" agency. They ensure through audits and reviews that funds raised are used in accordance with the stated intentions. ',
            'stod-90-3' => 'The conditions are stated as follows: "The organization [The ornitological society of Skåne] has received a 90 account for a part of their ongoing work related to bird research, bird protection and public awareness raising in the area of birds and birds migration, all under the umbrella of Falsterbo Bird Observatory.  fågelforskning, fågelskydd samt undervisning om fåglar och fågelflyttning allt i regi av Falsterbo Fågelstation. Funds raised must be used for the stated purpose at the Bird observatory and a detailed annual report must be submitted to "The Swedish Fundraising Control".',
            'stod-90-nummer' => 'Pg 900301-3, Bg 900-3013, SKÅNES ORNITOLOGISKA FÖRENING',
            'stod-reach' => 'Your support reach the birds',
            'stod-90-huvudman' => 'Skånes Ornitologiska Förening (SkOF) is the account owner of the "90 account". Kindly, therefore put down Skånes Ornitologiska Förening (SkOF) as recipient when using the 90-accounts.',
            'MINNESGÅVA' => '',
            'minnesgava-header' => 'Memory gift',
            'HYLLNINGSGÅVA' => '',
            'hyllningsgava-header' => 'Gift donation',
            'hyllningsgava-motiv' => 'Motifs',
            'hyllningsgava-para-1' => 'Struggling for ideas for a present? You can give the gift of a donation to Falsterbo Bird Observatory. Money can be transferred to our 90-account (bg 900-3013, pg 900301-3, Skånes Ornitologiska Förening), then select from one of the cards below.',
            'hyllningsgava-para-2' => 'As soon as our bank has received the transfer, the gift is sent to the address provided.',
            'hyllningsgava-para-3' => '',
            'BIDRAG' => '',
            'bidrag-header' => 'Immediate support',
            'bidrag-intro-1' => 'This is the easiest way to support the bird observatory. At the same time you become a "Falsterbo Bird Friend" (Falsterbo Fågelvän).',
            'bidrag-intro-2' => 'You can send any amount you wish to Bg 900-3013 or Pg 900301-3, recipient Skånes Ornitologiska Förening.',
            'bidrag-intro-3' => 'Please state "Gift" and name, telephone number and email when you transferring funds.',
            'bidrag-intro-4' => 'A donation will automatically make you a "Falsterbo Bird Friend, FBF" (unless you already are). As a FBF you will receive the bird observatory newsletter (issued 2-3 times a year) and other information material.',
            'bidrag-fv-1' => 'Falsterbo Bird Friend - Falsterbo Fågelvän - what is it?',
            'bidrag-fv-2' => 'What is the purpose with Falsterbo Bird Friend?',
            'bidrag-fv-3' => 'The purpose is to strengthen Falsterbo Fågelstation economically through public support, in a pace suitable and decided by each contributor individually. In this way you become a longer term supporter and contribute to letting us being able to be the spokesmen for the birds.',
            'bidrag-fv-4' => 'Who is a Falsterbo Fågelvän?',
            'bidrag-fv-5' => 'Anyone who decides to financially contribute to our work, regardless of sum.',
            'bidrag-fv-6' => 'If you already are a contributor and is known by us you will automatically also become Falsterbo Fågelvän.',
            'bidrag-fv-7' => 'How do we keep track of our Falsterbo Fågelvänner?',
            'bidrag-fv-8' => 'We have a database with those who have contributed to our work. The data we collect and keep is: first name, last name, telephone number, e-mail address and date for the most recent contribution.',
            'bidrag-fv-9' => 'How do we communicate with our Falsterbo Fågelvänner?',
            'bidrag-fv-10' => 'As a Falsterbo Fågelvän you periodically receive information from us:',
            'bidrag-fv-l-1' => 'Newsletter from Falsterbo Bird observatory (at least 3 times per year)',
            'bidrag-fv-l-2' => 'Annual reports from the bird observatory, among them visible migration report (sträckräkning) and ringing report.',
            'bidrag-fv-l-3' => 'Other particularly interesting information about our work (irregularly)',
            'bidrag-fv-l-4' => 'All outreach is digital. Nothing is sent through normal mail.',
            'bidrag-fv-11' => 'For how long do I remain a Falsterbo Fågelvän?',
            'bidrag-fv-2-1' => 'We run annual checks of our database. Those who have not contributed during the last three years, will receive a alert, and thus be given to contribute again. If this does not happen, the person will be pruned from the database.',
            'bidrag-fv-2-2' => 'Man kan aktivt höra av sig till oss (via mail eller telefon) och säga att man vill bli bortplockad ur vårt register.',
            'bidrag-fv-12' => 'Any further questions?',
            'bidrag-fv-13' => 'Contact Björn Malmhagen 0703-339499 or Karin Persson 040-473703.',
            'bidrag-swish-1' => 'You can also Swish money to us using number: 123 196 2455.',
            'bidrag-swish-2' => 'If you swish, we wold be grateful for a short email where you tell us who you are. Please send this to <a href="mailto:falsterbo@skof.se">falsterbo@skof.se</a>. ',
            'ARVSGÅVA' => '',
            'arvsgava-header' => 'Leave assets by a will',
            'arvsgava-para-1' => 'Your will is your final wish and has a huge impact once You are gone. You can, completely or partly, leave assets by a will to Falsterbo Bird Observatory. By doing this, you will contribute to stimulate interest for nature in future generations, and thereby also create a better future for our birds.',
            'arvsgava-para-2' => 'Setting up a will is quite straight forward. Writing with your own words "This is how I want my assets to be divided when I am no more among you..."',
            'arvsgava-para-3' => 'However, there are certain formal requirements and therefore we recommend You to contact Your bank or lawyer.',
            'arvsgava-data' => 'Required information',
            'arvsgava-gåvomottagare' => 'Gift receiver',
            'arvsgava-organisationsnummer' => 'Organisation number',
            'arvsgava-bankgiro' => 'Bankgiro',
            'arvsgava-betalningsmottagare' => 'Payment receiver',
            'arvsgava-contact' => 'Contact persons',
            'INTER' => '',
            'inter-header' => 'International collaboration',
            'inter-text-1' => 'Falsterbo fågelstation has signed a formal friendship agreement between us, <a href="https://njaudubon.org/centers/cape-may-bird-observatory/">New Jersey Audubon\'s Cape May Bird Observatory</a> (USA), <a href="https://www.birdscanada.org/longpoint/">Long Point Bird Observatory</a> (Kanada) och <a href="https://www.spurnbirdobservatory.co.uk/">Spurn Bird Observatory</a> (UK). The aim with this agreement is to promote international collaboration to stimulate increased environmental awareness.',
            'inter-text-2' => 'Our staff or collaborators and our members will benefit from this by discounts for staying at these collaborating bird observatories with the aim to increase the knowledge about bird migration at the international level. Below you can see the agreement which will be guiding the future work. Together we will express how and why our work is relevant for developing new methodologies for replying to new and pressing questions about birds, their living environment and ultimately, their protection for future generations.',
            'inter-perspektiv' => 'Views of the friendship agreement',
            'JUL' => '',
            'julgava-header' => 'Christmas gift',
        );

        return $texts;
    }

    function getTxt($txt){
        return $this->texts[$txt];
    }


}